input:
  metadata: /path/to/sample_metadata.tsv

  dada2:
    seqtabfile: /path/to/seqtab.rds
    taxafile: /path/to/taxa.rds
    reftreefile: /path/to/reftree.tree

  qiime2:
    otuqzafile: /path/to/otu.qza
    taxaqzafile: /path/to/taxa.qza
    treeqzafile: /path/to/tree.qza

  metaphlan:
    profile: /path/to/metaphlan_profile.tsv # all level or species level

  picrust2:
    ecprofile: /path/to/picrust2/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz
    koprofile: /path/to/picrust2/KO_metagenome_out/pred_metagenome_unstrat.tsv.gz
    pathprofile: /path/to/picrust2/pathways_out/path_abun_unstrat.tsv.gz


params:
  import_from: "qiime2" # choose from ["qiime2", "dada2", "metaphlan"]
  group: "donor_status" # update it based on the metadata information

  filter:
    min_abun: 1
    min_prop: 0.1
    Phylum: ["p__un_k__Bacteria", "p__un_k__d__Bacteria"]
    Class: [""]
    Order: [""]
    Family: [""]
    Genus: [""]
    OTU: [""]

  rarefy:
    filtered_samples: ["sample_id1", "sample_id2"]
    chunks: 500
    plot:
      width: 20 
      height: 5
    
  composition:
    level: ["Phylum", "Class", "Order", "Family", "Genus", "OTU"]
    plot:
      abundance:
        Phylum:
          width: 10
          height: 10
        Class: 
          width: 10
          height: 10
        Order:
          width: 10
          height: 10
        Family:
          width: 10
          height: 10
        Genus:
          width: 10
          height: 10
        OTU:
          width: 15
          height: 15
      abundance_group:
        Phylum:
          width: 10
          height: 10
        Class:
          width: 10
          height: 10
        Order:
          width: 10
          height: 10
        Family:
          width: 10
          height: 10
        Genus:
          width: 10
          height: 10
        OTU:
          width: 15
          height: 15
      heatmap:
        Phylum:
          width: 30
          height: 10
        Class:
          width: 30
          height: 10
        Order:
          width: 30
          height: 10
        Family:
          width: 30
          height: 10
        Genus:
          width: 30
          height: 10
        OTU:
          width: 30
          height: 10

  venn:
    plot:
      width: 10
      height: 10
 
  diversity_alpha:
    plot:
      width: 15
      height: 10

  diversity_phylogenetic:
    do: True
    plot:
      width: 15
      height: 6

  diversity_beta:
    distmethod: "bray" # ["bray", "euclidean"]
    plot:
      dist_samples:
        width: 12
        height: 10
      dist_groups:
        width: 6 
        height: 6
      pca:
        width: 12
        height: 5
      pcoa:
        width: 12
        height: 5
      nmds:
        width: 12
        height: 5
      clust:
        width: 12
        height: 10

  diff:
    first_test_method: "kruskal_test"  # ["kruskal.test", "oneway.test", "lm", "glm", "glm.nb", "kruskal_test", "oneway_test"]
    first_test_alpha: 0.05
    filter_p: "pvalue"                 # ["fdr", "pvalue"]
    strict: True
    fc_method: "generalizedFC"         # ["compare_mean", "generalizedFC"]
    second_test_method: "wilcox_test"  # ["wilcox.test", "wilcox_test", "glm", "glm.nb"]
    second_test_alpha: 0.05
    subcl_min: 3
    subcl_test: TRUE
    ml_method: "lda"
    ldascore: 3
    plot:
      tree:
        width: 20
        height: 20
      cladogram:
        width: 20
        height: 20
      box_bar:
        width: 20
        height: 20
      mahattan:
        width: 15
        height: 8

  diff_plus:
    methods: ["edgeR_quasi_likelihood", "edgeR_likelihood_ratio", "edger_robust_likelihood_ratio", "deseq2", "limma_voom", "limma_voom_sample_weights"]
    formula: "~donor_status"
    plot:
      abundance:
        do: False
        height: 10
        width: 10
      sample_tree:
        do: False
        height: 10
        width: 10
      otu_tree:
        do: False
        height: 10
        width: 10

  diff_zicoseq:
    plot:
      tree:
        width: 20
        height: 20
      cladogram:
        width: 20
        height: 20
      box_bar:
        width: 20
        height: 20
      mahattan:
        width: 15
        height: 8

  function:
    do: True
    abundance:
      plot:
        abundance:
          ec:
            height: 10
            width: 10
          ko:
            height: 10
            width: 10
          path:
            height: 10
            width: 10
        abundance_group:
          ec:
            height: 10
            width: 10
          ko:
            height: 10
            width: 10
          path:
            height: 10
            width: 10
        heatmap:
          ec:
            height: 10
            width: 10
          ko:
            height: 10
            width: 10
          path:
            height: 10
            width: 10
    enrichment:
      plot:
        dot:
          height: 6 
          width: 8
        network:
          height: 6 
          width: 10
 

output:
  import: "results/00.import"
  rarefied: "results/00.rarefied"
  composition: "results/01.composition"
  venn: "results/01.venn"
  diversity_alpha: "results/02.diversity_alpha"
  diversity_phylogenetic: "results/02.diversity_phylogenetic"
  diversity_beta: "results/03.diversity_beta"
  permanova: "results/04.permanova"
  diff: "results/05.diff"
  diff_plus: "results/05.diff_plus"
  diff_zicoseq: "results/05.diff_zicoseq"
  function: "results/06.function"


envs:
  mpse: "envs/mpse.yaml"