input:
  metadata: /path/to/sample_metadata.tsv

  dada2:
    seqtabfile: /path/to/seqtab.rds
    taxafile: /path/to/taxa.rds

  qiime2:
    otuqzafile: /path/to/otu.qza
    taxaqzafile: /path/to/taxa.qza

  metaphlan:
    profile: /path/to/metaphlan_profile.tsv # all level or species level


params:
  import_from: "qiime2" # choose from ["qiime2", "dada2", "metaphlan"]

  group: "Time" # update it based on the metadata information

  rarefy:
    filtered_samples: ["sample_id1", "sample_id2"]
    chunks: 500
    plot:
      width: 10
      height: 10

  diversity_alpha:
    plot:
      width: 10
      height: 10

  diversity_beta:
    distmethod: "bray"

  diff:
    first_test_alpha: "0.01"



output:
  import: "results/00.import"
  rarefied: "results/00.rarefied"
  composition: "results/01.composition"
  diversity_alpha: "results/02.diversity_alpha"
  diversity_beta: "results/03.diversity_beta"
  diff: "results/04.diff"


envs:
  mpse: "envs/mpse.yaml"